### ISSUE TITLE
Release 0.1 checklist

### ISSUE THREAD

**Issue by shreyasbapat** [einsteinpy/einsteinpy#83]
### Before release

- [x]  Rerun notebooks

- [x]  Complete Changelog

- [x]   Add future branch to CI scripts

- [x]   New branch

- [x]   Bump version in:
  - `README.rst`
  - `__init__.py`
  - Sphinx `conf.py`
  - AppVeyor CI script

- [x]   Check that the release branch will be tested on CI

- [x]   Check all the badges in `README` point to the appropriate git **branch** (replace `master` by new branch `sed -i 's/master/.../g' README.rst`)

- [x]  Check that docs badges and URLs point to appropriate **tag** (replace `latest` by new tag, without sed!)

- [x]  Commit

- [x]   Generate sdist and bdist_wheel

- [x]   `twine upload dist/* --repository-url https://test.pypi.org/legacy/`

- [x]   Tag

- [x]   Bump master to next development version

- [x]   Cherry pick the changelog with the release date

### Release

- [x]   Push branch to GitHub **and tags**

- [x]   Upload sdist and bdist_wheel to PyPI - *this step cannot be undone if the release is removed!* `twine upload dist/* --repository-url https://upload.pypi.org/legacy/`

- [x]  Build conda-forge feedstock

- [x]  Create GitHub release

- [x]  Check Read the Docs (might take a while)

- [x]  Add Zenodo badge to GitHub release

- [x]  Send announcement email

- [x]  Add link to announcement email in GitHub release

- [x]  Close milestone

**Comment by shreyasbapat** [comment]
### Before Alpha 1 release

- [ ]  Rerun notebooks

- [ ]  Complete Changelog

- [ ]   Add future branch to CI scripts

- [ ]   New branch

- [ ]   Bump version in:
  - `README.rst`
  - `__init__.py`
  - Sphinx `conf.py`
  - AppVeyor CI script

- [ ]   Check that the release branch will be tested on CI

- [ ]   Check all the badges in `README` point to the appropriate git **branch** (replace `master` by new branch `sed -i 's/master/.../g' README.rst`)

- [ ]  Check that docs badges and URLs point to appropriate **tag** (replace `latest` by new tag, without sed!)

- [ ]  Commit

- [ ]   Generate sdist and bdist_wheel

- [ ]   `twine upload dist/* --repository-url https://test.pypi.org/legacy/`

- [ ]   Tag

- [ ]   Bump master to next development version

- [ ]   Cherry pick the changelog with the release date

### Release

- [ ]   Push branch to GitHub **and tags**

- [ ]   Upload sdist and bdist_wheel to PyPI - *this step cannot be undone if the release is removed!* `twine upload dist/* --repository-url https://upload.pypi.org/legacy/`

- [ ]  Build conda-forge feedstock

- [ ]  Create GitHub release

- [ ]  Check Read the Docs (might take a while)

- [ ]  Add Zenodo badge to GitHub release

- [ ]  Send announcement email

- [ ]  Add link to announcement email in GitHub release

- [ ]  Close milestone

**Comment by shreyasbapat** [comment]
Test Pypi Release: https://test.pypi.org/project/einsteinpy/

**Comment by shreyasbapat** [comment]
Pypi release: https://pypi.org/project/einsteinpy/

**Comment by shreyasbapat** [comment]
@Masquerade0097 I think we should not loose this day!

**Comment by Masquerade0097** [comment]
@shreyasbapat I have made the PR https://github.com/conda-forge/staged-recipes/pull/7943. Working on fix the build.

**Comment by shreyasbapat** [comment]
https://github.com/conda-forge/einsteinpy-feedstock
